version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Top-level requirements.txt
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    groups:
      security-updates:
        applies-to: "security-updates"
        name: "root-security"
      version-updates:
        applies-to: "version-updates"
        name: "root-updates"

  - package-ecosystem: "pip"
    directory: "/my_app"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    groups:
      security-updates:
        applies-to: "security-updates"
        name: "api-security"
      version-updates:
        applies-to: "version-updates"
        name: "api-updates"

  - package-ecosystem: "pip"
    directory: "/pages"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    groups:
      security-updates:
        applies-to: "security-updates"
        name: "auth-security"
      version-updates:
        applies-to: "version-updates"
        name: "auth-updates"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
