version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Top-level requirements.txt
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    groups:
      root-security:
        applies-to: "security-updates"
      root-updates:
        applies-to: "version-updates"

  - package-ecosystem: "pip"
    directory: "/my_app"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    groups:
      api-security:
        applies-to: "security-updates"
      api-updates:
        applies-to: "version-updates"

  - package-ecosystem: "pip"
    directory: "/pages"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    groups:
      auth-security:
        applies-to: "security-updates"
      auth-updates:
        applies-to: "version-updates"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      gh-actions-security:
        applies-to: "security-updates"
      gh-actions-updates:
        applies-to: "version-updates"
